  CREATE TABLE EAI_SERVICE_CONFIGURATOR (DOMAIN VARCHAR2(250), TARGET VARCHAR2(250), SERVICE VARCHAR2(250), VERSION VARCHAR2(250))
/
  ALTER TABLE EAI_SERVICE_CONFIGURATOR ADD CONSTRAINT EAI_SERVICE_CONFIGURATOR_PK PRIMARY KEY (DOMAIN, TARGET, SERVICE, VERSION) ENABLE
/
  ALTER TABLE EAI_SERVICE_CONFIGURATOR MODIFY (DOMAIN NOT NULL ENABLE)
/
  ALTER TABLE EAI_SERVICE_CONFIGURATOR MODIFY (TARGET NOT NULL ENABLE)
/
  ALTER TABLE EAI_SERVICE_CONFIGURATOR MODIFY (SERVICE NOT NULL ENABLE)
/
  ALTER TABLE EAI_SERVICE_CONFIGURATOR MODIFY (VERSION NOT NULL ENABLE)
/
  
  CREATE TABLE EAI_SERVICE_CONFIGURATOR_PARAM (DOMAIN VARCHAR2(250), TARGET VARCHAR2(250), SERVICE VARCHAR2(250), VERSION VARCHAR2(250), PARAM_NAME VARCHAR2(4000), PARAM_VALUE VARCHAR2(4000), ID VARCHAR2(250))
/
  ALTER TABLE EAI_SERVICE_CONFIGURATOR_PARAM ADD CONSTRAINT EAI_SERVICE_CONFIG_PARAM_PK PRIMARY KEY (ID) ENABLE
/
  ALTER TABLE EAI_SERVICE_CONFIGURATOR_PARAM ADD CONSTRAINT EAI_SERVICE_CONFIGURATOR_FK1 FOREIGN KEY (DOMAIN, TARGET, SERVICE, VERSION) 
  REFERENCES EAI_SERVICE_CONFIGURATOR (DOMAIN, TARGET, SERVICE, VERSION) ON DELETE CASCADE ENABLE
/

EXIT