<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/VFIE-OSS/SOAFramework/getAsyncEvent" name="getAsyncEvent-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="getAsyncEvent.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/VFIE-OSS/SOAFramework/getAsyncEvent"/>
    <wsdl:binding name="getAsyncEvent_ptt-binding" type="get:getAsyncEvent_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/VFIE-OSS/SOAFramework/getAsyncEvent">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="getAsyncEvent">
            <soap:operation soapAction="getAsyncEvent"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>