CREATE TABLESPACE tablespace_SOAF_EVENTS DATAFILE 'tablespace_SOAF_EVENTS_01.dbf' SIZE 5M AUTOEXTEND ON;
    
CREATE TEMPORARY TABLESPACE temp_tablespace_SOAF_EVENTS  TEMPFILE 'temp_SOAF_EVENTS_01.dbf' SIZE 5M AUTOEXTEND ON;

CREATE USER SOAF_EVENTS
  IDENTIFIED BY SOAF_EVENTS
   DEFAULT TABLESPACE tablespace_SOAF_EVENTS
  TEMPORARY TABLESPACE temp_tablespace_SOAF_EVENTS
  QUOTA unlimited on tablespace_SOAF_EVENTS;
 
  
GRANT create session TO SOAF_EVENTS;
GRANT create table TO SOAF_EVENTS;
GRANT create view TO SOAF_EVENTS;
GRANT create any trigger TO SOAF_EVENTS;
GRANT create any procedure TO SOAF_EVENTS;
GRANT create sequence TO SOAF_EVENTS;
GRANT create synonym TO SOAF_EVENTS;
