
 /* TABLES */  
 
  CREATE TABLE "SOAF_EVENT_CONFIG" 
   (	"CONFIG_ID" VARCHAR2(250 BYTE), 
	"EVENT_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"TARGET_DOMAIN" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"TARGET_CATEGORY" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"TARGET_SERVICE" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"TARGET_SERVICE_VERSION" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"XSLT_MAPPING" CLOB, 
	"LAST_UPDATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("CONFIG_ID")
	 );
   
   
   
  CREATE TABLE "SOAF_EVENT_ACTIONS" 
   (	
   "ACTION_ID" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"CONFIG_ID" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"EVENT_ID" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"SERVICE_CORRELATION_ID" VARCHAR2(250 BYTE), 
	"CUSTOMER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"EVENT_REQUEST" CLOB, 
	"ACTION_REQUEST" CLOB, 
	"ACTION_STATE" VARCHAR2(50 BYTE), 
	"ACTION_STATUS_CODE" VARCHAR2(20 BYTE), 
	"ACTION_STATUS_MESSAGE" VARCHAR2(250 BYTE), 
	"RETRY_COUNT" CHAR(1 BYTE) NOT NULL ENABLE, 
	"ACTION_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"ACTION_LAST_UPDATE" TIMESTAMP (6) NOT NULL ENABLE, 
	PRIMARY KEY ("ACTION_ID"),
	CONSTRAINT "SOAF_EVENT_ACTIONS_FK1" FOREIGN KEY ("CONFIG_ID")
	REFERENCES "SOAF_EVENT_CONFIG" ("CONFIG_ID") ENABLE
	
	);
	  
	   
   

 /* SEQUENCE & TRIGGERS */ 
 
 
   
   CREATE SEQUENCE event_action_id_seq START WITH 1;
   
   CREATE OR REPLACE TRIGGER event_action_id_trg 
	BEFORE INSERT ON SOAF_EVENT_ACTIONS 
	FOR EACH ROW

	BEGIN
	  SELECT event_action_id_seq.NEXTVAL
	  INTO   :new.ACTION_ID
	  FROM   dual;
	END;
/
