   
 /* STORED PROCEDURES */  
 
 
create or replace PACKAGE "PKG_SOAF_EVENT_HANDLING" AS

PROCEDURE GET_EVENT_CONFIG(
        I_EVENT_NAME IN VARCHAR2,
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        O_CONFIG_ID OUT NUMBER,
        O_EVENT_NAME OUT VARCHAR2,
        O_TARGET_DOMAIN OUT VARCHAR2,
        O_TARGET_CATEGORY OUT VARCHAR2,
        O_TARGET_SERVICE OUT VARCHAR2,
        O_TARGET_SERVICE_VERSION OUT VARCHAR2,
		O_XSLT_MAPPING OUT CLOB,
        O_LAST_UPDATE OUT VARCHAR2,
        O_USERNAME OUT VARCHAR2);

PROCEDURE NEW_EVENT(
        I_EVENT_NAME IN VARCHAR2,
        I_CUSTOMER_ID IN VARCHAR2,
        I_EVENT_DETAILS IN CLOB,
        
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        O_ACTION_ID OUT VARCHAR2,
        O_CONFIG_ID OUT VARCHAR2,
        O_EVENT_ID OUT VARCHAR2,
        O_EVENT_REQUEST OUT VARCHAR2,
        O_ACTION_STATE OUT VARCHAR2,
        O_RETRY_COUNT OUT VARCHAR2,
		O_ACTION_CREATE_DATE OUT VARCHAR2,
        O_ACTION_LAST_UPDATE OUT VARCHAR2
        );

END PKG_SOAF_EVENT_HANDLING;
 
 
 /
 
 
create or replace PACKAGE BODY "PKG_SOAF_EVENT_HANDLING" AS



-- GET_EVENT_CONFIG
PROCEDURE GET_EVENT_CONFIG(
        I_EVENT_NAME IN VARCHAR2,
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        O_CONFIG_ID OUT NUMBER,
        O_EVENT_NAME OUT VARCHAR2,
        O_TARGET_DOMAIN OUT VARCHAR2,
        O_TARGET_CATEGORY OUT VARCHAR2,
        O_TARGET_SERVICE OUT VARCHAR2,
        O_TARGET_SERVICE_VERSION OUT VARCHAR2,
		O_XSLT_MAPPING OUT CLOB,
        O_LAST_UPDATE OUT VARCHAR2,
        O_USERNAME OUT VARCHAR2)
IS
  ERR_NUM       NUMBER; 
  ERR_MSG       VARCHAR2(100);  

BEGIN
  SELECT CONFIG_ID, EVENT_NAME, TARGET_DOMAIN, TARGET_CATEGORY, TARGET_SERVICE, TARGET_SERVICE_VERSION, LAST_UPDATE, USERNAME,XSLT_MAPPING
  INTO O_CONFIG_ID, O_EVENT_NAME, O_TARGET_DOMAIN, O_TARGET_CATEGORY, O_TARGET_SERVICE, O_TARGET_SERVICE_VERSION, O_LAST_UPDATE, O_USERNAME,O_XSLT_MAPPING
  FROM SOAF_EVENT_CONFIG WHERE EVENT_NAME = I_EVENT_NAME;


  O_ERRORCODE        := 0;
  O_ERRORTEXT        := 'Success';

EXCEPTION
WHEN OTHERS THEN
  --rollback;
  ERR_NUM      := SQLCODE;
  ERR_MSG      := SUBSTR(SQLERRM, 1, 100);
  O_ERRORCODE := 4;
  O_ERRORTEXT := 'GET_EVENT_CONFIG - Generic error: ' || err_num || '-' || err_msg;
  DBMS_OUTPUT.PUT_LINE(ERR_NUM || '-' || ERR_MSG);
  END GET_EVENT_CONFIG; 




-- NEW_EVENT
PROCEDURE NEW_EVENT(
        I_EVENT_NAME IN VARCHAR2,
        I_CUSTOMER_ID IN VARCHAR2,
        I_EVENT_DETAILS IN CLOB,
        
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        O_ACTION_ID OUT VARCHAR2,
        O_CONFIG_ID OUT VARCHAR2,
        O_EVENT_ID OUT VARCHAR2,
        O_EVENT_REQUEST OUT VARCHAR2,
        O_ACTION_STATE OUT VARCHAR2,
        O_RETRY_COUNT OUT VARCHAR2,
		O_ACTION_CREATE_DATE OUT VARCHAR2,
        O_ACTION_LAST_UPDATE OUT VARCHAR2
        )
IS
    ERR_NUM     NUMBER; 
    ERR_MSG     VARCHAR2(100);  
    EVENT_ID    VARCHAR2(40);

BEGIN
    EVENT_ID:=SYS_GUID();

    INSERT INTO SOAF_EVENT_ACTIONS ACT (ACT.CONFIG_ID, ACT.EVENT_ID, ACT.CUSTOMER_ID, ACT.EVENT_REQUEST, ACT.ACTION_STATE, ACT.RETRY_COUNT, ACT.ACTION_CREATE_DATE, ACT.ACTION_LAST_UPDATE)
    SELECT CONFIG_ID, EVENT_ID, I_CUSTOMER_ID, I_EVENT_DETAILS, 'NEW', '0', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
    FROM SOAF_EVENT_CONFIG WHERE EVENT_NAME = I_EVENT_NAME;
  


IF SQL%ROWCOUNT > 0 then
  O_ERRORCODE        := 0;
  O_ERRORTEXT        := 'Success';
  O_EVENT_ID         := EVENT_ID;
ELSE
 O_ERRORCODE        := 2;
 O_ERRORTEXT        := 'NEW_EVENT - Event Name not found in SOAF_EVENT_CONFIG';
END IF;

EXCEPTION    
WHEN OTHERS THEN
  --rollback;
  ERR_NUM      := SQLCODE;
  ERR_MSG      := SUBSTR(SQLERRM, 1, 100);
  O_ERRORCODE := 4;
  O_ERRORTEXT := 'NEW_EVENT - Generic error: ' || err_num || '-' || err_msg;
  DBMS_OUTPUT.PUT_LINE(ERR_NUM || '-' || ERR_MSG);
  END NEW_EVENT; 

END PKG_SOAF_EVENT_HANDLING;

/