--------------------------------------------------------
--  File created - Segunda-Feira-Agosto-01-2016   
--------------------------------------------------------

Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (2,'ALL','ALL','ALL','ALL','ALL','ALL','LOG_LEVEL','DEBUG');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (1,'ALL','ALL','ALL','ALL','ALL','ALL','LOG_LEVEL_SYSTEM','DEBUG');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (3,'ALL','ALL','ALL','ALL','ALL','ALL','LOG_LEVEL_EVENT','INFO');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (4,'ALL','ALL','proxyServices','ALL','ALL','ALL','ERROR_MASKING_HEADER','SOAFramework/soaf/common/transformations/proxyService/backendResultsToHeader');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (5,'Provisioning','gdsp','proxyServices','provisioningStatus','ALL','ALL','ERROR_MASKING_HEADER',null);
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (6,'ALL','ALL','java','ALL','ALL','ALL','publisher.schedulerFrequencyInSeconds','30');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (7,'ALL','ALL','java','ALL','ALL','ALL','publisher.timeoutSeconds','180');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (8,'ALL','ALL','java','ALL','ALL','ALL','publisher.maxNumberOfRequests','100');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (9,'ALL','ALL','ALL','CachePublish','ALL','ALL','cache.security_credentials','welcome1');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (10,'ALL','ALL','java','ALL','ALL','ALL','publisher.password','welcome1');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (11,'ALL','ALL','ALL','CachePublish','ALL','ALL','cache.security_principal','weblogic');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (12,'ALL','ALL','java','ALL','ALL','ALL','publisher.username','weblogic');
Insert into SOAF_SERVICE_CONFIGURATOR (ID,DOMAIN,CATEGORY,TARGET,SERVICE,VERSION,USERNAME,PARAM_NAME,PARAM_VALUE) values (13,'ALL','ALL','ALL','CachePublish','ALL','ALL','cache.provider_url','t3://localhost:7101');