<wsdl:definitions targetNamespace="http://xmlns.telco.com/SIGFramework/eventHandling/pub/newEvent/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.telco.com/SIGFramework/eventHandling/pub/newEvent/v1" xmlns:c="http://xmlns.telco.com/SOAFramework/soaf/common/schemas/commonTypes/v1">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://xmlns.telco.com/SIGFramework/eventHandling/pub/newEvent/v1" schemaLocation="../schemas/newEvent.xsd" />
      <xsd:import namespace="http://xmlns.telco.com/SOAFramework/soaf/common/schemas/commonTypes/v1" schemaLocation="../../../../../SOAFramework/soaf/common/schemas/commonTypes_v1.xsd" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="newEvent_v1Request">
    <wsdl:part name="requestServiceHeader" element="c:serviceHeader" />
    <wsdl:part name="requestParameters" element="tns:newEventRequest" />
  </wsdl:message>
  <wsdl:message name="newEvent_v1Response">
    <wsdl:part name="responseServiceHeader" element="c:serviceHeader" />
    <wsdl:part name="responseParameters" element="tns:newEventResponse" />
  </wsdl:message>
  <wsdl:portType name="newEvent_ptt">
    <wsdl:operation name="newEvent_v1">
      <wsdl:input message="tns:newEvent_v1Request" />
      <wsdl:output message="tns:newEvent_v1Response" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="newEvent_binding" type="tns:newEvent_ptt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="newEvent_v1">
      <soap:operation soapAction="http://www.example.org/eventHandling/newEvent_v1" />
      <wsdl:input>
        <soap:body use="literal" parts="requestParameters" />
        <soap:header message="tns:newEvent_v1Request" part="requestServiceHeader" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="responseParameters" />
        <soap:header message="tns:newEvent_v1Response" part="responseServiceHeader" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="newEvent_service">
    <wsdl:port name="newEvent" binding="tns:newEvent_binding">
      <soap:address location="http://localhost:7001/SIGFramework/eventHandling/pub/newEvent_v1/newEvent" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
