SET SERVEROUTPUT ON

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', 'LOG_LEVEL_SYSTEM', 'INFO') --Available levels: ALL, TRACE, DEBUG, INFO, WARN, ERROR, OFF
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', 'LOG_LEVEL', 'DEBUG')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', 'LOG_LEVEL_EVENT', 'INFO')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'proxyServices', 'ALL', 'ALL', 'ALL', 'ERROR_MASKING_HEADER', 'OSBCommon/common/xquery/errorManagement/getDefaultPublicReturnCodes')
/

--No masking error for this service / status used in body context
INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'Provisioning', 'gdsp', 'proxyServices', 'provisioningStatus', 'ALL', 'ALL', 'ERROR_MASKING_HEADER', '')
/
INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'Provisioning', 'gdsp', 'proxyServices', 'provisioningStatus', 'ALL', 'ALL', 'ERROR_MASKING_BODY', 'Provisioning/gdsp/callback/provisioningStatus_v1/transformation/fromProvisioningStatus')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'Provisioning', 'ALL', 'ALL', 'uploadAndProvisionBatchFile', 'ALL', 'ALL', 'LOG_WRITE_BODY', 'false')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'Provisioning', 'ALL', 'ALL', 'uploadOrderReturnBatchFile', 'ALL', 'ALL', 'LOG_WRITE_BODY', 'false')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'Provisioning', 'ALL', 'ALL', 'uploadSimBatchFile', 'ALL', 'ALL', 'LOG_WRITE_BODY', 'false')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'java', 'ALL', 'ALL', 'ALL', 'publisher.republishEventUrl', 'http://localhost:7001/SOAFramework/soaf/callback/publisherCallback_v1/publisherCallback')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'java', 'ALL', 'ALL', 'ALL', 'publisher.timeoutSeconds', '180')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'java', 'ALL', 'ALL', 'ALL', 'publisher.username', 'weblogic')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'java', 'ALL', 'ALL', 'ALL', 'publisher.password', 'welcome1')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'java', 'ALL', 'ALL', 'ALL', 'publisher.schedulerFrequencyInSeconds', '30')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'java', 'ALL', 'ALL', 'ALL', 'publisher.maxNumberOfRequests', '100')
/

--Retry all errors for 3 times with 180 seconds between retry
INSERT INTO SOAF_REPUBLISHER_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, MAX_NUMBER_OF_RETRIES, ERROR_CODE, SECONDS_BETWEEN_RETRIES)
VALUES  (SOAF_REPUBLISHER_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', 3, '%', 180)
/

--Clean cache of soaf-osb-db persistence store:
INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'CachePublish', 'ALL', 'ALL', 'cache.provider_url', 't3://localhost:7001')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'CachePublish', 'ALL', 'ALL', 'cache.security_principal', 'weblogic')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'CachePublish', 'ALL', 'ALL', 'cache.security_credentials', 'welcome1')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'CachePublish', 'ALL', 'ALL', 'cache.provider_jms_connection_factory', 'jms/soaf-osb-connection-factory')
/

INSERT INTO SOAF_SERVICE_CONFIGURATOR (ID, DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, USERNAME, PARAM_NAME, PARAM_VALUE)
VALUES (SOAF_SERVICE_CONF_ID_SEQ.NEXTVAL, 'ALL', 'ALL', 'ALL', 'CachePublish', 'ALL', 'ALL', 'cache.provider_jms_topic_name', 'jms/soaf-osb-db-cache-clean-topic')
/

EXIT
