SET SERVEROUTPUT ON

--------------------------------------------------------
--  DDL for Table SOAF_REPUBLISHER_CONFIGURATOR
--------------------------------------------------------
CREATE SEQUENCE SOAF_REPUBLISHER_CONF_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE TABLE SOAF_REPUBLISHER_CONFIGURATOR 
(	
	ID NUMBER, 
    DOMAIN VARCHAR2(250 BYTE) NOT NULL,
	CATEGORY VARCHAR2(250 BYTE) NOT NULL,
	TARGET VARCHAR2(250 BYTE) NOT NULL,
	SERVICE VARCHAR2(250 BYTE) NOT NULL,
	VERSION VARCHAR2(10 BYTE) NOT NULL,
	MAX_NUMBER_OF_RETRIES NUMBER,
	ERROR_CODE VARCHAR2(250 BYTE),
	SECONDS_BETWEEN_RETRIES NUMBER,
  CONSTRAINT SOAF_REPUBLISHER_CONF_PK PRIMARY KEY (ID) ENABLE 
)  
/

ALTER TABLE SOAF_REPUBLISHER_CONFIGURATOR
ADD CONSTRAINT SOAF_REPUBLISHER_CONF_OP_UK UNIQUE(DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, ERROR_CODE) ENABLE
/

--------------------------------------------------------
--  DDL for Table SOAF_REPUBLISHER
--------------------------------------------------------
CREATE SEQUENCE SOAF_REPUBLISHER_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE TABLE SOAF_REPUBLISHER 
(	
	ID NUMBER, 
	MESSAGE_ID VARCHAR2(250 BYTE) NOT NULL,
	REQUEST_ID VARCHAR2(250 BYTE), 
	CORRELATION_ID VARCHAR2(250 BYTE), 
	ERROR_CODE VARCHAR2(250 BYTE),
    ERROR_MESSAGE VARCHAR2(4000),
	STATUS VARCHAR2(20 BYTE),
	REQUEST CLOB NOT NULL,
	REPUB_INFO CLOB,
	DOMAIN VARCHAR2(250 BYTE) NOT NULL,
	CATEGORY VARCHAR2(250 BYTE) NOT NULL,
	TARGET VARCHAR2(250 BYTE) NOT NULL,
	SERVICE VARCHAR2(250 BYTE) NOT NULL,
	VERSION VARCHAR2(10 BYTE) NOT NULL,
	CREATED_DATE TIMESTAMP (6) NOT NULL,
	CREATED_BY VARCHAR2(250 BYTE) NOT NULL,
	LAST_UPDATED_DATE TIMESTAMP (6) NOT NULL,
	LAST_UPDATED_BY VARCHAR2(250 BYTE) NOT NULL,
	NUMBER_OF_RETRIES NUMBER,
  CONSTRAINT SOAF_REPUBLISHER_PK PRIMARY KEY (ID) ENABLE 
)  
/

--------------------------------------------------------
--  DDL for Table EAI_SERVICE_CONFIGURATOR
--------------------------------------------------------
CREATE SEQUENCE SOAF_SERVICE_CONF_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE TABLE SOAF_SERVICE_CONFIGURATOR (
  ID NUMBER  NOT NULL,
  DOMAIN VARCHAR2(250) NOT NULL,
  CATEGORY VARCHAR2(250) NOT NULL,
  TARGET VARCHAR2(250) NOT NULL,
  SERVICE VARCHAR2(250) NOT NULL,
  VERSION VARCHAR2(250)  NOT NULL,
  USERNAME VARCHAR2(250) NOT NULL,
  PARAM_NAME VARCHAR2(4000)  NOT NULL,
  PARAM_VALUE VARCHAR2(4000),
  CONSTRAINT SOAF_SERVICE_CONFIGURATOR_PK PRIMARY KEY (ID) ENABLE 
)
/

ALTER TABLE SOAF_SERVICE_CONFIGURATOR
ADD CONSTRAINT SOAF_SERVICE_CONFIGURATOR_UK UNIQUE(DOMAIN, CATEGORY, TARGET, SERVICE, VERSION, PARAM_NAME) ENABLE
/

--------------------------------------------------------
--  Function to identify the most specific configuration
--------------------------------------------------------
CREATE FUNCTION CALCULATE_DOMAIN_WEIGHT(ID IN NUMBER, DOMAIN IN VARCHAR2, CATEGORY IN VARCHAR2, TARGET IN VARCHAR2, VERSION IN VARCHAR2, USERNAME IN VARCHAR2) 
   RETURN NUMBER 
   IS DOMAIN_WEIGHT NUMBER(12) := 0;
   BEGIN 
    IF DOMAIN <> 'ALL' THEN
      DOMAIN_WEIGHT := DOMAIN_WEIGHT + 10000000000;
    END IF;
    IF CATEGORY <> 'ALL' THEN
      DOMAIN_WEIGHT := DOMAIN_WEIGHT + 20000000000;
    END IF;
    IF TARGET <> 'ALL' THEN
      DOMAIN_WEIGHT := DOMAIN_WEIGHT + 30000000000;
    END IF;
    IF VERSION <> 'ALL' THEN
      DOMAIN_WEIGHT := DOMAIN_WEIGHT + 40000000000;
    END IF;
	IF USERNAME <> 'ALL' THEN
      DOMAIN_WEIGHT := DOMAIN_WEIGHT + 50000000000;
    END IF;
    
    RETURN(DOMAIN_WEIGHT + ID);
END;
/

--------------------------------------------------------
--  DDL for Table SOAF_ASYNC_EVENTS
--------------------------------------------------------
  CREATE TABLE "SOAF_ASYNC_EVENTS" 
   ( "ID" NUMBER PRIMARY KEY, 
	"REQUEST_ID" VARCHAR2(250 BYTE), 
	"CORRELATION_ID" VARCHAR2(250 BYTE), 
	"EXTERNAL_CORRELATION_ID" VARCHAR2(250 BYTE), 
	"PAYLOAD_REQUEST" CLOB,
	"PAYLOAD_RESPONSE" CLOB, 		
	"TARGET_SERVICE" VARCHAR2(250 BYTE), 
	"CREATE_TIME" TIMESTAMP (6),
	"ASYNC_RESPONSE_TIME" TIMESTAMP (6)
	)  
/

CREATE SEQUENCE SOAF_ASYNC_EVENTS_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/


--------------------------------------------------------
--  DDL for Table SOAF_BACKEND_SIMULATOR
--------------------------------------------------------
  CREATE TABLE "SOAF_BACKEND_SIMULATOR" (
	"ID" NUMBER NOT NULL ENABLE, 
	"NS_OPERATION" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"XPATH_VALIDATION" VARCHAR2(500 BYTE), 
	"SERVICE" VARCHAR2(250 BYTE), 
	"RESPONSE_BODY" CLOB,
	"RESPONSE_HEADER" CLOB,
	CONSTRAINT "SOAF_BACKEND_SIMULATOR_PK" PRIMARY KEY ("ID")
	)
/

EXIT