--------------------------------------------------------
--  File created - Quarta-feira-Fevereiro-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package PKG_SOAF
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PKG_SOAF" AS 

    PROCEDURE CREATE_ASYNC_EVENT(
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        I_REQUEST_ID IN VARCHAR2,
        I_CORRELATION_ID IN VARCHAR2,
        I_EXTERNAL_CORRELATION_ID IN VARCHAR2,
        I_PAYLOAD_REQUEST IN CLOB,
        I_TARGET_SERVICE IN VARCHAR2);
        
    PROCEDURE GET_ASYNC_EVENT(
        I_EXTERNAL_CORRELATION_ID IN VARCHAR2,
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        O_ID OUT NUMBER,
        O_REQUEST_ID OUT VARCHAR2,
        O_CORRELATION_ID OUT VARCHAR2,
        O_PAYLOAD_REQUEST OUT CLOB,
        O_PAYLOAD_RESPONSE OUT CLOB,
        O_TARGET_SERVICE OUT VARCHAR2,
        O_CREATE_TIME OUT TIMESTAMP,
        O_ASYNC_RESPONSE_TIME OUT TIMESTAMP);

END PKG_SOAF;

/

--------------------------------------------------------
--  File created - Quarta-feira-Fevereiro-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body PKG_SOAF
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "PKG_SOAF" AS


PROCEDURE CREATE_ASYNC_EVENT(O_ERRORCODE OUT NUMBER, O_ERRORTEXT OUT VARCHAR2, I_REQUEST_ID IN VARCHAR2, I_CORRELATION_ID IN VARCHAR2, I_EXTERNAL_CORRELATION_ID IN VARCHAR2, I_PAYLOAD_REQUEST IN CLOB, I_TARGET_SERVICE IN VARCHAR2)
IS
  ERR_NUM       NUMBER; 
  ERR_MSG       VARCHAR2(100);  

BEGIN
  INSERT INTO SOAF_ASYNC_EVENTS (ID, REQUEST_ID, CORRELATION_ID, EXTERNAL_CORRELATION_ID, PAYLOAD_REQUEST, TARGET_SERVICE, CREATE_TIME) 
  VALUES (SOAF_ASYNC_EVENTS_ID_SEQ.NEXTVAL, I_REQUEST_ID, I_CORRELATION_ID, I_EXTERNAL_CORRELATION_ID, I_PAYLOAD_REQUEST, I_TARGET_SERVICE, SYSTIMESTAMP);
  O_ERRORCODE        := 0;
  O_ERRORTEXT        := 'Success';
      
EXCEPTION
WHEN OTHERS THEN
  --rollback;
  ERR_NUM      := SQLCODE;
  ERR_MSG      := SUBSTR(SQLERRM, 1, 100);
  O_ERRORCODE := 4;
  O_ERRORTEXT := 'CREATE_ASYNC_EVENT - Generic error: ' || err_num || '-' || err_msg;
  DBMS_OUTPUT.PUT_LINE(ERR_NUM || '-' || ERR_MSG);
END CREATE_ASYNC_EVENT;
  


PROCEDURE GET_ASYNC_EVENT(I_EXTERNAL_CORRELATION_ID IN VARCHAR2, O_ERRORCODE OUT NUMBER, O_ERRORTEXT OUT VARCHAR2, O_ID OUT NUMBER, O_REQUEST_ID OUT VARCHAR2, O_CORRELATION_ID OUT VARCHAR2, O_PAYLOAD_REQUEST OUT CLOB, O_PAYLOAD_RESPONSE OUT CLOB, O_TARGET_SERVICE OUT VARCHAR2, O_CREATE_TIME OUT TIMESTAMP, O_ASYNC_RESPONSE_TIME OUT TIMESTAMP)
IS
  ERR_NUM       NUMBER; 
  ERR_MSG       VARCHAR2(100);  

BEGIN
  SELECT ID, REQUEST_ID, CORRELATION_ID, PAYLOAD_REQUEST, PAYLOAD_RESPONSE, TARGET_SERVICE, CREATE_TIME, ASYNC_RESPONSE_TIME
  INTO O_ID, O_REQUEST_ID, O_CORRELATION_ID, O_PAYLOAD_REQUEST, O_PAYLOAD_RESPONSE, O_TARGET_SERVICE, O_CREATE_TIME, O_ASYNC_RESPONSE_TIME
  FROM SOAF_ASYNC_EVENTS WHERE EXTERNAL_CORRELATION_ID = I_EXTERNAL_CORRELATION_ID;
  UPDATE SOAF_ASYNC_EVENTS SET ASYNC_RESPONSE_TIME = SYSTIMESTAMP WHERE ID = O_ID;
  O_ERRORCODE        := 0;
  O_ERRORTEXT        := 'Success';
     
EXCEPTION
WHEN OTHERS THEN
  --rollback;
  ERR_NUM      := SQLCODE;
  ERR_MSG      := SUBSTR(SQLERRM, 1, 100);
  O_ERRORCODE := 4;
  O_ERRORTEXT := 'GET_ASYNC_EVENT - Generic error: ' || err_num || '-' || err_msg;
  DBMS_OUTPUT.PUT_LINE(ERR_NUM || '-' || ERR_MSG);
  END GET_ASYNC_EVENT; 


END PKG_SOAF;

/

--------------------------------------------------------
--  File created - Quarta-feira-Fevereiro-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package PKG_SOAF_BACKEND_SIMULATOR
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PKG_SOAF_BACKEND_SIMULATOR" AS 


PROCEDURE GET_SIMULATION (
        I_NS_OPERATION IN VARCHAR2,
        I_REQUEST IN VARCHAR2,
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        O_ID OUT NUMBER,
        O_RESPONSE_BODY OUT VARCHAR2,
        O_RESPONSE_HEADER OUT VARCHAR2,
        O_SERVICE OUT VARCHAR2
);

END PKG_SOAF_BACKEND_SIMULATOR;

/

--------------------------------------------------------
--  File created - Quarta-feira-Fevereiro-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body PKG_SOAF_BACKEND_SIMULATOR
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "PKG_SOAF_BACKEND_SIMULATOR" AS

PROCEDURE GET_SIMULATION (
        I_NS_OPERATION IN VARCHAR2,
        I_REQUEST IN VARCHAR2,
        O_ERRORCODE OUT NUMBER,
        O_ERRORTEXT OUT VARCHAR2,
        O_ID OUT NUMBER,
        O_RESPONSE_BODY OUT VARCHAR2,
        O_RESPONSE_HEADER OUT VARCHAR2,
        O_SERVICE OUT VARCHAR2
        )
        
IS
  ERR_NUM       NUMBER; 
  ERR_MSG       VARCHAR2(100);
  N_POSSIBLE_RESULTS NUMBER;

BEGIN

  SELECT ID, SERVICE, RESPONSE_BODY, RESPONSE_HEADER INTO O_ID, O_SERVICE, O_RESPONSE_BODY, O_RESPONSE_HEADER FROM (
    SELECT ''||EXTRACT( XMLTYPE(I_REQUEST), XPATH_VALIDATION) AS XPATH_RESULT, ID, SERVICE, RESPONSE_BODY, RESPONSE_HEADER FROM (
      SELECT * FROM SOAF_BACKEND_SIMULATOR WHERE NS_OPERATION = I_NS_OPERATION AND XPATH_VALIDATION IS NOT NULL
    )
  ) WHERE XPATH_RESULT IS NOT NULL;


  O_ERRORCODE        := 0;
  O_ERRORTEXT        := 'Success';
    
EXCEPTION

WHEN NO_DATA_FOUND THEN
  O_ERRORCODE        := 0;
  O_ERRORTEXT        := 'Success';
  SELECT ID, SERVICE, RESPONSE_BODY, RESPONSE_HEADER INTO O_ID, O_SERVICE, O_RESPONSE_BODY, O_RESPONSE_HEADER FROM SOAF_BACKEND_SIMULATOR
  WHERE NS_OPERATION = I_NS_OPERATION AND XPATH_VALIDATION IS NULL;
  
WHEN OTHERS THEN
  ERR_NUM      := SQLCODE;
  ERR_MSG      := SUBSTR(SQLERRM, 1, 100);
  O_ERRORCODE := 4;
  O_ERRORTEXT := 'GET_SIMULATION - Generic error: ' || err_num || '-' || err_msg;
  DBMS_OUTPUT.PUT_LINE(ERR_NUM || '-' || ERR_MSG);
  
END GET_SIMULATION;
  
END PKG_SOAF_BACKEND_SIMULATOR;

/

COMMIT;

/