DROP USER SOAF_LOGGER;

CREATE TABLESPACE tablespace_SOAF_LOGGER DATAFILE 'tablespace_SOAF_LOGGER_01.dbf' SIZE unlimited;
    
CREATE TEMPORARY TABLESPACE temp_tablespace_SOAF_LOGGER  TEMPFILE 'temp_SOAF_LOGGER_01.dbf' SIZE 5M AUTOEXTEND ON;

CREATE USER SOAF_LOGGER
  IDENTIFIED BY SOAF_LOGGER
   DEFAULT TABLESPACE tablespace_SOAF_LOGGER
  TEMPORARY TABLESPACE temp_tablespace_SOAF_LOGGER
  QUOTA unlimited on tablespace_SOAF_LOGGER;
 
  
GRANT create session TO SOAF_LOGGER;
GRANT create table TO SOAF_LOGGER;
GRANT create view TO SOAF_LOGGER;
GRANT create any trigger TO SOAF_LOGGER;
GRANT create any procedure TO SOAF_LOGGER;
GRANT create sequence TO SOAF_LOGGER;
GRANT create synonym TO SOAF_LOGGER;
